### ISSUE TITLE
ConnectionRefusedError / IncompatibleProtocolError

### ISSUE THREAD

**Issue by skytect** [mosquito/aio-pika#161] opened 2018-11-15 20:40 UTC
When I try to connect to a server on aio-pika, it raises `ConnectionRefusedError`. Sometimes, it also raises `IncompatibleProtocolError`. However, when I try to connect to the same server on pika, it works fine. Both pika and aio-pika also work fine when I connect to localhost.

### pika code
```
import pika

def connect(url):
    return pika.BlockingConnection(pika.connection.URLParameters(url))

if __name__ == '__main__':
    username = '...'
    password = '...'
    server = 'api.[domain name].com'
    url = f'amqps://{username}:{password}@{server}:5673/?socket_timeout=10'
    # url = 'amqp://127.0.0.1/'  # This works
    print(connect(url))  # Prints <BlockingConnection impl=<SelectConnection OPEN socket=('[Local IP]', 54792)->('[Server IP]', 5673) params=<URLParameters host=api.[domain name].com port=5673 virtual_host=/ ssl=True>>>
```

### aio-pika code
```
import asyncio
import aio_pika

async def connect(url):
    async with await aio_pika.connect(url) as conn:
        print(conn)

if __name__ == '__main__':
    username = '...'
    password = '...'
    server = 'api.[domain name].com'
    url = f'amqps://{username}:{password}@{server}:5673/?socket_timeout=10'
    # url = 'amqp://127.0.0.1/'  # This works
    asyncio.run(connect(url))
```

### `ConnectionRefusedError` when using aio_pika
```
Traceback (most recent call last):
  File "/path/to/script.py", line 14, in <module>
    asyncio.run(connect(url))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/path/to/script.py", line 5, in connect
    async with await aio_pika.connect(url) as conn:
  File "/path/to/site-packages/aio_pika/connection.py", line 437, in connect
    await connection.connect()
  File "/path/to/site-packages/aio_pika/connection.py", line 232, in connect
    result = await f
ConnectionRefusedError: Connection to [IPv4 address]:5673 failed: timeout
```

### `IncompatibleProtocolError` when using aio_pika
```
Traceback (most recent call last):
  File "/path/to/site-packages/aio_pika/pika/adapters/base_connection.py", line 384, in _handle_read
    data = self.socket.recv(self._buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/script.py", line 14, in <module>
    asyncio.run(connect(url))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/path/to/script.py", line 5, in connect
    async with await aio_pika.connect(url) as conn:
  File "/path/to/site-packages/aio_pika/connection.py", line 437, in connect
    await connection.connect()
  File "/path/to/site-packages/aio_pika/connection.py", line 232, in connect
    result = await f
  File "/path/to/site-packages/aio_pika/adapter.py", line 157, in _handle_disconnect
    super()._handle_disconnect()
  File "/path/to/site-packages/aio_pika/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/path/to/site-packages/aio_pika/adapter.py", line 153, in _adapter_disconnect
    super()._adapter_disconnect()
  File "/path/to/site-packages/aio_pika/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/path/to/site-packages/aio_pika/pika/adapters/base_connection.py", line 169, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
aio_pika.pika.exceptions.IncompatibleProtocolError
```

### Versions
* Python 3.7.1
* I installed aio-pika and pika through pipenv:
```
aio-pika==4.3.1
  - shortuuid [required: Any, installed: 0.5.0]
  - yarl [required: Any, installed: 1.2.6]
    - idna [required: >=2.0, installed: 2.7]
    - multidict [required: >=4.0, installed: 4.4.2]
pika==0.12.0
```

**Comment by mosquito** [comment] 2018-11-19 21:56
You should specify SSL options for the `aio-pika` I guess.

**Comment by mosquito** [comment] 2018-11-19 21:58
And "yes" it's weakly documented. ☹️

**Comment by OrangeTux** [comment] 2018-11-30 15:54
I also ran into this issue. And I would argue that is is a bug.

I expected the following snippets seem to produce the same results, but they don't. Do you agree that this is confusion?

``` python
# Will connect without errors
connection = await connect(
    host=server,
    login=username,
    password=password,
    ssl=True,
    port=5671,
)
```

``` python
# Will raise IncompatibleProtocolError
connection = await connect(f'amqps://{username}:{password}@{server}:5671')
```

I suggest to change the body of [connect](https://github.com/mosquito/aio-pika/blob/master/aio_pika/connection.py#L431) from:

``` python
 ssl = bool(ssl_options)
```

to:

``` python
ssl = url.scheme.lower() == 'amqps'
```

**Comment by tilsche** [comment] 2018-12-03 08:45
Seems like a duplicate of #134 (which has #135 as a fix) but is not merged/closed yet.

**Comment by OrangeTux** [comment] 2018-12-03 08:49
I see now. I'll close PR. Thanks for noticing.

**Closed** 2020-09-15 14:05 UTC
